### ISSUE TITLE
isyndemo lfc command fails with fatal error.

### ISSUE THREAD

**Issue by bhishanpdl** [deanishe/i-sheet-you-not#2]
The command `isyndemo lfc` fails with Fatal Error.

Alfred version: 3.6.2
Date: Aug 25, 2018

The error is given below:

```
ascii codec can't decode byte 0xc2 in position
ordinal not in range (128)
```

**Comment by deanishe** [comment]
Fixed in [v0.3.2](https://github.com/deanishe/i-sheet-you-not/releases/tag/v0.3.2)
