### ISSUE TITLE
Ideas on how to use this workflow

### ISSUE THREAD

**Issue by firesofmay** [deanishe/i-sheet-you-not#3]
Hi,

This workflow sounds very interesting! It would be great if you shared how you use it personally, and what use cases do you think would be great for this workflow in the readme file.

Thanks

**Comment by deanishe** [comment]
I don't really use it personally. The workflow is aimed at non-developers, as an Excel-based alternative to Alfred's List Filters.

I think [the demo is a fairly good example of what you can do with it](https://www.deanishe.net/i-sheet-you-not/).
